# Generated by Django 5.0.4 on 2024-04-30 06:35

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_name", models.CharField(max_length=300)),
                ("User_phone", models.BigIntegerField()),
                ("User_address", models.CharField(max_length=300)),
                ("User_pic", models.FileField(upload_to="media/reportimages")),
            ],
        ),
        migrations.CreateModel(
            name="WebcamImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/reportimages")),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("work", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("contact", models.PositiveBigIntegerField()),
                ("comment", models.CharField(max_length=50)),
                ("pdfname", models.CharField(default="none", max_length=50)),
                (
                    "image",
                    models.FileField(
                        default="", upload_to=App.models.generate_filename
                    ),
                ),
                ("docname", models.CharField(default="none", max_length=50)),
                (
                    "document",
                    models.FileField(default="", upload_to="media/reportimages"),
                ),
                ("othername", models.CharField(default="", max_length=50)),
                ("other", models.FileField(default="", upload_to="media/reportimages")),
                ("othername1", models.CharField(default="", max_length=50)),
                (
                    "other1",
                    models.FileField(default="", upload_to="media/reportimages"),
                ),
            ],
        ),
    ]
