# Generated by Django 5.0.2 on 2024-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="admin",
            field=models.CharField(default="main", max_length=50),
        ),
    ]
