# Generated by Django 5.0.2 on 2024-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_work_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="admin",
            field=models.CharField(max_length=50),
        ),
    ]
