# Generated by Django 5.0.2 on 2024-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_work_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
