# Generated by Django 5.0.2 on 2024-06-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="place",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="App.place"
            ),
        ),
    ]
