# Generated by Django 5.0.2 on 2024-06-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_work_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="place",
        ),
    ]
