# Generated by Django 5.0.2 on 2024-06-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_work_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="work",
            name="dis",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="App.dis"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="vil",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="App.vil"
            ),
        ),
    ]
