# Generated by Django 5.0.2 on 2024-06-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_dis_vil_work_dis_work_vil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="title",
        ),
    ]
