# Generated by Django 5.0.2 on 2024-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_remove_work_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="bl",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="ca",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="fp",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="op",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="su",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="tp",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="un",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="work",
            name="wo",
            field=models.CharField(default="", max_length=50),
        ),
    ]
