# Generated by Django 5.0.2 on 2024-06-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0010_work_bl_work_ca_work_fp_work_op_work_su_work_tp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="work",
            name="admin",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="App.admin"
            ),
        ),
    ]
