# Generated by Django 5.0.2 on 2024-06-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0011_admin_alter_work_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="description",
        ),
    ]
