# Generated by Django 5.0.2 on 2024-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_remove_work_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="comment",
        ),
        migrations.AddField(
            model_name="work",
            name="diss",
            field=models.CharField(default=21, max_length=50),
            preserve_default=False,
        ),
    ]
