# Generated by Django 5.0.2 on 2024-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_remove_work_comment_work_diss"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="tal",
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="work",
            name="vils",
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
