# Generated by Django 5.0.2 on 2024-06-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0014_work_tal_work_vils"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="dis",
        ),
        migrations.RemoveField(
            model_name="work",
            name="place",
        ),
        migrations.RemoveField(
            model_name="work",
            name="vil",
        ),
    ]
