# Generated by Django 5.0.2 on 2024-06-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0015_remove_work_dis_remove_work_place_remove_work_vil"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dis",
        ),
        migrations.DeleteModel(
            name="Place",
        ),
        migrations.DeleteModel(
            name="Vil",
        ),
    ]
