# Generated by Django 5.0.2 on 2024-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0016_delete_dis_delete_place_delete_vil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="contact",
            field=models.PositiveBigIntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name="work",
            name="diss",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="tal",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="vils",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="work",
            field=models.CharField(default="", max_length=50),
        ),
    ]
