# Generated by Django 5.0.2 on 2024-06-10 10:05

import App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0017_alter_work_contact_alter_work_diss_alter_work_tal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="App.admin",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="bl",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="ca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="diss",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="media/reportimages"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="fp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=App.models.generate_filename
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="op",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="other",
            field=models.FileField(
                blank=True, null=True, upload_to="media/reportimages"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="other1",
            field=models.FileField(
                blank=True, null=True, upload_to="media/reportimages"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="othername",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="othername1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="pdfname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="su",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="tal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="tp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="un",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="vils",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="wo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="work",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
