# Generated by Django 5.0.2 on 2024-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0018_alter_work_admin_alter_work_bl_alter_work_ca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="docname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
