# Generated by Django 5.0.2 on 2024-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0019_alter_work_docname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="bl",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="ca",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="diss",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="docname",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="fp",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="name",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="op",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="othername",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="othername1",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="pdfname",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="su",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="tal",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="tp",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="un",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="vils",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="wo",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="work",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
