# Generated by Django 5.0.2 on 2024-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0021_alter_work_bl_alter_work_ca_alter_work_diss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="work",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
