# Generated by Django 5.0.2 on 2024-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0022_alter_work_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="media/reportimages"
            ),
        ),
    ]
