# Generated by Django 5.0.2 on 2024-06-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0023_alter_work_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="comment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
