# Generated by Django 5.0.2 on 2024-08-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0026_alter_work_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="App.admin"
            ),
        ),
    ]
