# Generated by Django 5.0.2 on 2024-08-23 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0029_remove_work_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="App.admin",
            ),
        ),
    ]
